import { Student, ActivityLog } from '../types/ojt';

export const studentsData: Student[] = [
  { 
    id: 1, 
    initials: 'EC', 
    name: 'Elena Cortez', 
    type: 'OJT', 
    school: 'Polytechnic University', 
    required: 400, remaining: 124, 
    status: 'ACTIVE' 
  },
  { 
    id: 2, 
    initials: 'MR', 
    name: 'Marcus Reyes', 
    type: 'SPES', 
    school: 'City National High', 
    required: 160, 
    remaining: 0, 
    status: 'COMPLETED' 
  },
  { 
    id: 3, 
    initials: 'AL', 
    name: 'Aisha Lim', 
    type: 'Work Immersion', 
    school: 'Science High School', 
    required: 80, 
    remaining: 45, 
    status: 'ACTIVE' 
  },
  { 
    id: 4, 
    initials: 'JS', 
    name: 'Julian Santos', 
    type: 'OJT', 
    school: 'Technological Institute', 
    required: 300, 
    remaining: 200, 
    status: 'ACTIVE' },
  { 
    id: 5, 
    initials: 'CB', 
    name: 'Chloe Bautista', 
    type: 'Work Immersion', 
    school: 'Laguna State University', 
    required: 80, 
    remaining: 10, 
    status: 'ACTIVE' 
  },
  { 
    id: 6, 
    initials: 'MG', 
    name: 'Miguel Garcia', 
    type: 'OJT', 
    school: 'De La Salle University', 
    required: 500, 
    remaining: 450, 
    status: 'ACTIVE' },
  { id: 7, 
    initials: 'JP', 
    name: 'Jasmine Perez', 
    type: 'SPES', 
    school: 'National High School', 
    required: 160, 
    remaining: 80, 
    status: 'ACTIVE' 
  },
  { 
    id: 8, 
    initials: 'RN', 
    name: 'Rafael Navarro', 
    type: 'OJT', 
    school: 'Mapua University', 
    required: 300, 
    remaining: 0, 
    status: 'COMPLETED' 
  },
  { 
    id: 9, 
    initials: 'LT', 
    name: 'Lia Torres', 
    type: 'Work Immersion', 
    school: 'Science High School', 
    required: 80, 
    remaining: 80, 
    status: 'INACTIVE' 
  },
  { 
    id: 10, 
    initials: 'DC', 
    name: 'Daniel Cruz', 
    type: 'OJT', 
    school: 'Polytechnic University', 
    required: 400, 
    remaining: 350, 
    status: 'ACTIVE' 
  },
  { id: 11, 
    initials: 'SV', 
    name: 'Sofia Villanueva', 
    type: 'SPES', 
    school: 'City National High', 
    required: 160, 
    remaining: 12, 
    status: 'ACTIVE' 
  },
  { 
    id: 12, 
    initials: 'EM', 
    name: 'Ethan Mendoza', 
    type: 'OJT', 
    school: 'Technological Institute', 
    required: 300, 
    remaining: 150, 
    status: 'ACTIVE' 
  },
  { 
    id: 13, 
    initials: 'IA', 
    name: 'Isabella Aquino', 
    type: 'Work Immersion', 
    school: 'Laguna State University', 
    required: 80, 
    remaining: 0, 
    status: 'COMPLETED' 
  },
  { 
    id: 14, 
    initials: 'GD', 
    name: 'Gabriel Diaz', 
    type: 'OJT', 
    school: 'Ateneo de Manila', 
    required: 400, 
    remaining: 280, 
    status: 'ACTIVE' },
  { 
    id: 15, 
    initials: 'MC', 
    name: 'Mia Castro', 
    type: 'SPES', 
    school: 'National High School', 
    required: 160, 
    remaining: 160, 
    status: 'INACTIVE' },
  { 
    id: 16, 
    initials: 'LR', 
    name: 'Lucas Ramos', 
    type: 'OJT', 
    school: 'Mapua University', 
    required: 500, 
    remaining: 50, 
    status: 'ACTIVE' },
];

export const activityLogs: ActivityLog[] = [
  { 
    id: 1, 
    date: 'Oct 24, 2023', 
    day: 'Tuesday', 
    initials: 'AJ', 
    name: 'Alex Johnson', 
    studentId: 'CS-2021-001', 
    timeIn: '08:00 AM', 
    timeOut: '05:05 PM', 
    duration: '9h 05m', 
    status: 'Verified' 
  },
  { 
    id: 2, 
    date: 'Oct 24, 2023', 
    day: 'Tuesday', 
    initials: 'SL', 
    name: 'Samantha Lee', 
    studentId: 'IT-2022-045', 
    timeIn: '08:15 AM', 
    timeOut: '--:--', 
    duration: '--', 
    status: 'Active' 
  },
  { 
    id: 3, 
    date: 'Oct 23, 2023', 
    day: 'Monday', 
    initials: 'MR', 
    name: 'Marcus Rodriguez', 
    studentId: 'CS-2021-112', 
    timeIn: '08:30 AM', 
    timeOut: '02:15 PM', 
    duration: '4h 45m', 
    status: 'Flagged', 
    isDurationAlert: true 
  },
  { 
    id: 4, 
    date: 'Oct 23, 2023', 
    day: 'Monday', 
    initials: 'EC', 
    name: 'Elena Cortez', 
    studentId: 'ENG-2020-089', 
    timeIn: '09:00 AM', 
    timeOut: '06:00 PM', 
    duration: '9h 00m', 
    status: 'Verified' 
  },
  { 
    id: 5, 
    date: 'Oct 23, 2023', 
    day: 'Monday', 
    initials: 'CB', 
    name: 'Chloe Bautista', 
    studentId: 'CS-2021-034', 
    timeIn: '07:45 AM', 
    timeOut: '04:30 PM', 
    duration: '8h 45m', 
    status: 'Verified' 
  },
  { 
    id: 6, 
    date: 'Oct 22, 2023', 
    day: 'Sunday', 
    initials: 'JS', 
    name: 'Julian Santos', 
    studentId: 'IT-2022-011', 
    timeIn: '10:00 AM', 
    timeOut: '--:--', 
    duration: '--', 
    status: 'Active' 
  },
  { 
    id: 7, 
    date: 'Oct 22, 2023', 
    day: 'Sunday', 
    initials: 'MG', 
    name: 'Miguel Garcia', 
    studentId: 'CS-2021-099', 
    timeIn: '06:30 AM', 
    timeOut: '08:45 PM', 
    duration: '14h 15m', 
    status: 'Flagged', 
    isDurationAlert: true 
  },
  { 
    id: 8, 
    date: 'Oct 21, 2023', 
    day: 'Saturday', 
    initials: 'AL', 
    name: 'Aisha Lim', 
    studentId: 'ENG-2020-102', 
    timeIn: '08:00 AM', 
    timeOut: '05:00 PM', 
    duration: '9h 00m', 
    status: 'Verified' 
  },
  { 
    id: 9, 
    date: 'Oct 21, 2023', 
    day: 'Saturday', 
    initials: 'JP', 
    name: 'Jasmine Perez', 
    studentId: 'IT-2022-077', 
    timeIn: '08:10 AM', 
    timeOut: '05:15 PM', 
    duration: '9h 05m', 
    status: 'Verified' 
  },
  { 
    id: 10, 
    date: 'Oct 20, 2023', 
    day: 'Friday', 
    initials: 'RN', 
    name: 'Rafael Navarro', 
    studentId: 'CS-2021-055', 
    timeIn: '09:00 AM', 
    timeOut: '06:30 PM', 
    duration: '9h 30m', 
    status: 'Verified' 
  },
  { 
    id: 11, 
    date: 'Oct 20, 2023', 
    day: 'Friday', 
    initials: 'LT', 
    name: 'Lia Torres', 
    studentId: 'ENG-2020-004', 
    timeIn: '07:50 AM', 
    timeOut: '04:00 PM', 
    duration: '8h 10m', 
    status: 'Verified' },
  { 
    id: 12, 
    date: 'Oct 19, 2023', 
    day: 'Thursday', 
    initials: 'DC', 
    name: 'Daniel Cruz', 
    studentId: 'IT-2022-120', 
    timeIn: '08:00 AM', 
    timeOut: '12:00 PM', 
    duration: '4h 00m', 
    status: 'Flagged', 
    isDurationAlert: true 
  },
];