"""first migrate

Revision ID: 10a2f09d06b4
Revises: 
Create Date: 2026-07-02 20:09:19.768330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa,sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10a2f09d06b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('user_information',
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('user_info_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_img', sa.JSON(), nullable=True),
    sa.Column('user_id_ufk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_ufk'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_info_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_information')
    op.drop_table('users')
    # ### end Alembic commands ###
